name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests-windows:
    name: Windows - Swift 5.10 - SPM
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Swift
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.10-release
          tag: 5.10-RELEASE
      - name: Build Windows
        run: swift test

  tests-darwin:
    name: macOS - Swift 5.10 - SPM
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 15.3.0
        run: sudo xcode-select -s /Applications/Xcode_15.3.app
      - name: Run tests
        run: swift test
